// import 'bootstrap/dist/css/bootstrap.min.css';
// import AuthorizationProvider from '@/app/components/AuthorizationProvide';
import AuthorizationProvider from '@/app/(pages)/components/AuthorizationProvide';
import '../../../style.css';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthorizationProvider>
        {children}
        </AuthorizationProvider>
      </body>
    </html>
  );
}
